"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-17030ki869qm@tch=qzn&4yqnfufzl*1lobi2_!+wug#^73%ri'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'yourdomain.com']

#to enforce cookies sent over HTTPS only
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

# to add additional browser-side protections.
X_FRAME_OPTIONS = 'DENY' #Prevents your site from being loaded in an <iframe>, defending against Clickjacking attacks.
SECURE_CONTENT_TYPE_NOSNIFF = True #Prevents browsers from guessing the content type of files, mitigating content-type sniffing vulnerabilities that could lead to XSS.
SECURE_BROWSER_XSS_FILTER = True #Obsolete in modern browsers, but enables the browser’s XSS filtering and help prevent cross-site scripting attacks.
# Application definition

INSTALLED_APPS = [
    'bookshelf.apps.BookshelfConfig',
    'relationship_app.apps.RelationshipAppConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'csp.middleware.CSPMiddleware', #add CSP to middleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

# Content security policy settings
#To ensure all content(scripts, styles etc) comes from the site's own origin
CSP_DEFAULT_SRC = ("'self'",)

# Specifically for scripts: allow self and potentially a trusted CDN or analytics script
CSP_SCRIPT_SRC = ("'self'",)

# Specifically for styles: allow self
CSP_STYLES_SRC = ("'self'",)

# For images: allow self and data URIs (often used for inline images/icons)
CSP_IMG_SRC = ("'self'","data:")

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Media settings for uploaded content (like profile photos)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#Update Settings to Use the Custom User Model
AUTH_USER_MODEL = 'bookshelf.CustomUser'

"""
Configure your Django application to support and enforce HTTPS, 
protecting the data transmitted between the client and the server. 
This includes setting up HTTPS redirects, configuring security-
related headers, and ensuring that your site is served securely.
"""

SECURE_SSL_REDIRECT = True #to redirect all non-HTTPS requests to HTTPS.
SECURE_HSTS_SECONDS = 31536000 #Set an appropriate value (e.g., 31536000 for one year) to instruct browsers to only access the site via HTTPS for the specified time.

# Set to True to include all subdomains in the HSTS policy and to allow preloading.
SECURE_HSTS_INCLUDE_SUBDOMAINS= True
SECURE_HSTS_PRELOAD = True